name: Bot Traffic Revenue 24-7

on:
  schedule:
    - cron: '0 */6 * * *' # Restart otomatis tiap 6 jam
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install firefox
          playwright install-deps firefox

      - name: Jalankan Bot
        run: python ads.py
        
