name: BotOtomatis

on:
  schedule:
    # Jalan otomatis tiap jam
    - cron: '0 * * * *'
  workflow_dispatch: # Tombol manual di tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Run Bot
        # Sudah disesuaikan dengan nama file kamu: ads.py
        run: python ads.py
        
