name: BotOtomatis

on:
  schedule:
    # Menjalankan script setiap 1 jam sekali secara otomatis
    - cron: '0 * * * *'
  workflow_dispatch: # Biar bisa kamu klik "Run" manual di tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Run Bot
        run: python bot.py
        
