name: BotOtomatis

on:
  schedule:
    # Jalan otomatis setiap jam
    - cron: '0 * * * *'
  workflow_dispatch: # Tombol manual di tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Cek Daftar File
        # Ini buat mastiin file bot.py emang ada di folder yang bener
        run: ls -R

      - name: Run Bot
        # Pastikan nama file di repo kamu emang 'bot.py' (huruf kecil semua)
        run: python bot.py
        
